export const BASE_URL = "http://localhost:8080"
export const ADMIN_BASE_URL = "http://localhost:8080/api/admin"
export const USER_BASE_URL = "http://localhost:8080/api/user"
export const TRAINER_BASE_URL = "http://localhost:8080/api/trainer"
export const CHAT_BASE_URL = "http://localhost:8080/api/chats"